name: Build and Test

on:
  pull_request:
  push:
    branches: [main, develop]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    name: Build and Test
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test.yml@self-hosted-runner
    permissions: write-all
    with:
      solution-name: 'Obligatorio.sln'
