name: Code Analysis

on:
  pull_request:
  push:
    branches: [main, develop]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  analysis:
    name: Code Analysis
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-code-analysis.yml@self-hosted-runner
    permissions: write-all
    with:
      solution-name: 'Obligatorio.sln'
